const ALERT = "ALERT";
const REFETCH_CHATS = "REFETCH_CHATS";

const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
/** In-call text only — broadcast to chat members, not persisted. */
const CALL_CHAT_MESSAGE = "CALL_CHAT_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

const MESSAGE_DELIVERED = "MESSAGE_DELIVERED";
const MARK_CHAT_READ = "MARK_CHAT_READ";
const MESSAGE_STATUS_UPDATE = "MESSAGE_STATUS_UPDATE";

const MESSAGE_EDITED = "MESSAGE_EDITED";
const MESSAGE_DELETED_EVERYONE = "MESSAGE_DELETED_EVERYONE";
const MESSAGE_HIDDEN_FOR_USER = "MESSAGE_HIDDEN_FOR_USER";

export {
  ALERT,
  REFETCH_CHATS,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  CALL_CHAT_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  MESSAGE_DELIVERED,
  MARK_CHAT_READ,
  MESSAGE_STATUS_UPDATE,
  MESSAGE_EDITED,
  MESSAGE_DELETED_EVERYONE,
  MESSAGE_HIDDEN_FOR_USER,
};
